// Builds bank.js from bank/*.json.
// Questions marked conf:"medium" stay in the source files but are left out of the app until a person checks them.
// Handbook references live in a separate ref field, so all of them can be removed in one step.
const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, 'bank');
const check = process.argv.includes('--check');
const all = [], errors = [], ids = new Set();
// bank/*.json holds Florida and national questions; bank/states/<xx>.json holds one state each.
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort()
  .concat(fs.existsSync(path.join(dir, 'states')) ? fs.readdirSync(path.join(dir, 'states')).filter(f => f.endsWith('.json')).sort().map(f => 'states/' + f) : []);
for (const f of files) {
  for (const q of JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'))) {
    const bad = m => errors.push(`${f} ${q.id}: ${m}`);
    if (ids.has(q.id)) bad('duplicate id'); ids.add(q.id);
    if (!(q.c >= 0 && q.c <= 3)) bad('c out of range');
    if (!(q.page === undefined || q.page === null || (Number.isInteger(q.page) && q.page >= 1 && q.page <= 100))) bad('page must be null or a handbook page number');
    for (const L of ['en', 'es']) {
      const d = q[L]; if (!d) { bad('missing ' + L); continue; }
      for (const k of ['q', 'h1', 'h2', 'p']) if (!d[k] || !String(d[k]).trim()) bad(`${L}.${k} empty`);
      if (!Array.isArray(d.o) || d.o.length !== 4 || d.o.some(x => !String(x).trim())) bad(L + '.o must be 4 options');
      else if (new Set(d.o).size !== 4) bad(L + '.o has duplicates');
    }
    all.push(q);
  }
}
const served = all.filter(q => q.conf === 'high').map(q => {
  const o = { id: q.id, scope: q.scope, cat: q.cat, sign: q.sign || null, c: q.c, en: q.en, es: q.es };
  // Page in the Florida handbook (English, rev. 08/2023). National questions get one too when the handbook covers them.
  if (Number.isInteger(q.page)) o.ref = { doc: 'FL', page: q.page };
  else if (q.scope !== 'US') o.ref = { doc: q.scope, page: null };
  return o;
});
const count = (a, k) => a.reduce((m, q) => (m[q[k]] = (m[q[k]] || 0) + 1, m), {});
console.log('source', all.length, '| served', served.length, '| held (medium)', all.length - served.length);
console.log('served by topic', JSON.stringify(count(served, 'cat')), '| by scope', JSON.stringify(count(served, 'scope')));
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }
const out = '// Generated by build-bank.js from bank/*.json. Do not edit by hand.\nwindow.PV_BANK=' + JSON.stringify(served) + ';\n';
const file = path.join(__dirname, 'bank.js');
if (check) { const same = fs.existsSync(file) && fs.readFileSync(file, 'utf8') === out; console.log(same ? 'bank.js is current' : 'bank.js is stale'); process.exit(same ? 0 : 1); }
fs.writeFileSync(file, out);
