// Merges translation files (<dir>/<lang>/<topic>.json: id -> {q,o,h1,h2,p}) into bank/<topic>.json as q[<lang>],
// and writes i18n.js from <dir>/<lang>/ui.json. Usage: node tools/merge-i18n.js <dir>
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..'), src = process.argv[2];
const LANGS = ['zh', 'vi', 'tl', 'ar', 'ht'];
const ui = {};
for (const L of LANGS) {
  const d = path.join(src, L); if (!fs.existsSync(d)) continue;
  for (const f of fs.readdirSync(d)) {
    if (f === 'ui.json') { ui[L] = JSON.parse(fs.readFileSync(path.join(d, f), 'utf8')); continue; }
    const bf = path.join(root, 'bank', f); if (!fs.existsSync(bf)) throw new Error('no bank file ' + f);
    const bank = JSON.parse(fs.readFileSync(bf, 'utf8')), tr = JSON.parse(fs.readFileSync(path.join(d, f), 'utf8'));
    let n = 0;
    for (const q of bank) {
      const x = tr[q.id]; if (!x) throw new Error(`${L} ${f}: missing ${q.id}`);
      if (!Array.isArray(x.o) || x.o.length !== 4) throw new Error(`${L} ${f} ${q.id}: needs 4 options`);
      q[L] = { q: x.q, o: x.o, h1: x.h1, h2: x.h2, p: x.p }; n++;
    }
    fs.writeFileSync(bf, JSON.stringify(bank, null, 2) + '\n');
    console.log(L, f, n);
  }
}
const en = JSON.parse(fs.readFileSync(path.join(src, 'ui-en.json'), 'utf8'));
for (const [L, u] of Object.entries(ui)) {
  const missing = Object.keys(en).filter(k => !u[k]); if (missing.length) throw new Error(`${L} ui missing ${missing.join(',')}`);
  for (const k of Object.keys(en)) for (const ph of (en[k].match(/\{[a-z]\}/g) || [])) if (!u[k].includes(ph)) throw new Error(`${L} ui ${k} lost ${ph}`);
}
fs.writeFileSync(path.join(root, 'i18n.js'), '// Interface text for Chinese, Vietnamese, Tagalog and Arabic. Generated by tools/merge-i18n.js.\nwindow.PV_UI=' + JSON.stringify(ui) + ';\n');
console.log('ui', Object.keys(ui).join(' ') || 'none');
