// Writes STATES.md: one row per state from state-info/ and bank/states/. Run after any change to either.
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const rows = [];
for (const f of fs.readdirSync(path.join(root, 'state-info')).sort()) {
  const s = JSON.parse(fs.readFileSync(path.join(root, 'state-info', f), 'utf8'));
  const bf = path.join(root, 'bank', 'states', f);
  const qs = fs.existsSync(bf) ? JSON.parse(fs.readFileSync(bf, 'utf8')) : [];
  const ex = s.exam || {};
  const exam = ex.questions || ex.pass || ex.passPercent
    ? `${ex.questions ?? '?'} q, pass ${ex.pass ?? '?'}${ex.passPercent ? ` (${ex.passPercent}%)` : ''}` : 'not found';
  const hb = s.handbook || {};
  const link = u => u ? `[link](${u})` : '—';
  rows.push(`| ${s.code} | ${s.name || ''} | ${qs.length} | ${qs.filter(q => q.conf === 'high').length} | ${exam} | ${link(hb.en)} | ${link(hb.es)} | ${s.verified ? 'yes' : 'no'} |`);
}
const out = `# States

Generated by \`node tools/states-report.js\` from \`state-info/\` and \`bank/states/\`. Do not edit by hand.

A state's questions are shown to learners only after each one is checked against that state's handbook
(\`conf\` set to \`high\`, \`page\` filled in). Until then the state shows "coming soon" and the national questions.
On 2026-10-09 every state except Arizona and New Hampshire was checked against its official handbook (their sites block downloads).
Questions the handbook or state law could not confirm stay held.

Florida's questions are in \`bank/*.json\` (checked against the handbook, rev. 08/2023, with page numbers).

| State | Name | Draft questions | Checked | Knowledge test | Handbook (EN) | Handbook (ES) | Verified |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}
`;
fs.writeFileSync(path.join(root, 'STATES.md'), out);
console.log('states', rows.length);
